// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using frontAIagent.Data;

#nullable disable

namespace frontAIagent.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("frontAIagent.Models.SavedProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalysisName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("analysis_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DirectoryPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("directory_path");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue(".py")
                        .HasColumnName("file_type");

                    b.Property<DateTime>("LastAnalyzed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_analyzed")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LogPath")
                        .HasColumnType("text")
                        .HasColumnName("log_path");

                    b.Property<string>("ProgramDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("program_description");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisName")
                        .HasDatabaseName("idx_saved_projects_analysis_name");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_saved_projects_created_at");

                    b.HasIndex("LastAnalyzed")
                        .HasDatabaseName("idx_saved_projects_last_analyzed");

                    b.ToTable("saved_projects", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
